"""Iceberg DDL (Spark SQL dialect) for the lakehouse tables.

Spark has no PRIMARY KEY clause for Iceberg tables; the key, the lineage fields and the
schema version are recorded as table properties so MERGE statements and audits can read
them back.
"""

from __future__ import annotations

from pydantic import BaseModel

from cairn_schemas.base import Row
from cairn_schemas.generate._fields import FieldSpec, TypeNode, fields_of

CATALOG = "cairn"


def _sql_string(value: str) -> str:
    """A Spark SQL string literal; Spark escapes with backslashes, not doubled quotes."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _type(node: TypeNode, extra: dict) -> str:
    if "iceberg_type" in extra:
        return str(extra["iceberg_type"])
    match node.kind:
        case "string":
            return "STRING"
        case "long":
            return "BIGINT"
        case "double":
            return "DOUBLE"
        case "boolean":
            return "BOOLEAN"
        case "timestamp":
            return "TIMESTAMP"
        case "array":
            assert node.item is not None
            return f"ARRAY<{_type(node.item, {})}>"
        case "map":
            assert node.item is not None
            return f"MAP<STRING, {_type(node.item, {})}>"
        case "enum":
            return "STRING"
        case "record":
            assert node.record is not None
            inner = ", ".join(f"{s.name}: {_type(s.type, s.extra)}" for s in fields_of(node.record))
            return f"STRUCT<{inner}>"
    raise AssertionError(node.kind)


def _column(spec: FieldSpec) -> str:
    comment = spec.description
    if spec.type.kind == "enum":
        comment = (
            (comment + " " if comment else "") + "One of: " + ", ".join(spec.type.symbols) + "."
        )
    parts = [f"  {spec.name} {_type(spec.type, spec.extra)}"]
    if not spec.nullable:
        parts.append("NOT NULL")
    if comment:
        parts.append(f"COMMENT {_sql_string(comment)}")
    return " ".join(parts)


def render(model: type[Row]) -> str:
    assert issubclass(model, BaseModel)
    columns = ",\n".join(_column(spec) for spec in fields_of(model))
    props = {
        "format-version": "2",
        "write.upsert.enabled": "true",
        "cairn.primary-key": ",".join(model.PRIMARY_KEY),
        "cairn.lineage-fields": ",".join(model.LINEAGE_FIELDS),
        "cairn.schema-version": str(model.model_fields["schema_version"].default),
        "cairn.model": f"cairn_schemas.models.{model.__name__}",
    }
    prop_lines = ",\n".join(f"  {_sql_string(k)} = {_sql_string(v)}" for k, v in props.items())
    lines = [
        f"-- Generated by `make schemas` from cairn_schemas.models.{model.__name__}. Do not edit.",
        f"CREATE TABLE IF NOT EXISTS {CATALOG}.{model.TABLE} (",
        columns,
        ")",
        "USING iceberg",
    ]
    if model.PARTITION_BY:
        lines.append(f"PARTITIONED BY ({', '.join(model.PARTITION_BY)})")
    lines += ["TBLPROPERTIES (", prop_lines, ");"]
    return "\n".join(lines) + "\n"
