"""Postgres DDL for the Stage 0 lakehouse stand-in.

At Stage 0 one Postgres database holds the seven contract tables (ADR-0003). The DDL is
generated from the same models that generate the Avro, Iceberg and JSON Schema targets,
so a field added to a model shows up in all four in one diff.

Type mapping: TEXT, BIGINT, DOUBLE PRECISION, BOOLEAN, TIMESTAMPTZ; TEXT[] for string
arrays; JSONB for maps, nested records and any other array; TEXT with a CHECK for enums;
a real PRIMARY KEY. A field may override its column type with ``postgres_type`` in
``json_schema_extra`` (the vector column uses REAL[]: float32, never searched, only
rebuilt from). Partition specs are Iceberg's concern and are recorded as a comment.
"""

from __future__ import annotations

import json
from typing import Any

from cairn_schemas.base import Row
from cairn_schemas.generate._fields import FieldSpec, TypeNode, fields_of


def _sql_string(value: str) -> str:
    """A standard SQL string literal: quotes are doubled."""
    return "'" + value.replace("'", "''") + "'"


def _type(node: TypeNode, extra: dict[str, Any]) -> str:
    if "postgres_type" in extra:
        return str(extra["postgres_type"])
    match node.kind:
        case "string" | "enum":
            return "TEXT"
        case "long":
            return "BIGINT"
        case "double":
            return "DOUBLE PRECISION"
        case "boolean":
            return "BOOLEAN"
        case "timestamp":
            return "TIMESTAMPTZ"
        case "array":
            assert node.item is not None
            return "TEXT[]" if node.item.kind == "string" else "JSONB"
        case "map" | "record":
            return "JSONB"
    raise AssertionError(node.kind)


def column_type(spec: FieldSpec) -> str:
    """The Postgres column type of a field; the platform reads this to adapt row values."""
    return _type(spec.type, spec.extra)


def jsonb_columns(model: type[Row]) -> frozenset[str]:
    """Fields stored as JSONB: maps, nested records and non-string arrays."""
    return frozenset(spec.name for spec in fields_of(model) if column_type(spec) == "JSONB")


def _default(spec: FieldSpec, ctype: str) -> str | None:
    if not spec.has_default or spec.default is None:
        return None
    value = spec.default
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int | float):
        return repr(value)
    if isinstance(value, str):
        return _sql_string(value)
    if value in ([], {}):
        if ctype == "TEXT[]":
            return "'{}'::TEXT[]"
        if ctype == "JSONB":
            return _sql_string(json.dumps(value)) + "::JSONB"
    return None


def _column(spec: FieldSpec) -> str:
    ctype = column_type(spec)
    parts = [f"  {spec.name} {ctype}"]
    if not spec.nullable:
        parts.append("NOT NULL")
    default = _default(spec, ctype)
    if default is not None:
        parts.append(f"DEFAULT {default}")
    if spec.type.kind == "enum":
        symbols = ", ".join(_sql_string(s) for s in spec.type.symbols)
        parts.append(f"CHECK ({spec.name} IN ({symbols}))")
    return " ".join(parts)


def render(model: type[Row]) -> str:
    specs = fields_of(model)
    columns = [_column(spec) for spec in specs]
    columns.append(f"  PRIMARY KEY ({', '.join(model.PRIMARY_KEY)})")
    doc = (model.__doc__ or "").strip().splitlines()[0] if model.__doc__ else model.__name__
    lineage = ", ".join(model.LINEAGE_FIELDS)
    lines = [
        f"-- Generated by `make schemas` from cairn_schemas.models.{model.__name__}. Do not edit.",
        f"-- Stage 0 lakehouse stand-in (ADR-0003). Lineage fields: {lineage}.",
    ]
    if model.PARTITION_BY:
        lines.append(
            f"-- Iceberg partition spec, not applied here: {', '.join(model.PARTITION_BY)}."
        )
    lines += [
        f"CREATE TABLE IF NOT EXISTS {model.TABLE} (",
        ",\n".join(columns),
        ");",
        f"COMMENT ON TABLE {model.TABLE} IS {_sql_string(doc)};",
    ]
    for spec in specs:
        if spec.description:
            lines.append(
                f"COMMENT ON COLUMN {model.TABLE}.{spec.name} IS {_sql_string(spec.description)};"
            )
    return "\n".join(lines) + "\n"


def render_all_in_spine_order(models: tuple[type[Row], ...]) -> str:
    """Every table in one script, in lineage-spine order. ``cairn migrate`` applies this."""
    return "\n".join(render(model) for model in models)
